# Generated by Django 6.0.5 on 2026-05-15 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Yonke',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('razon_social', models.CharField(blank=True, max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('direccion', models.TextField(blank=True)),
                ('contacto_principal', models.CharField(blank=True, max_length=150)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('suspendido', 'Suspendido'), ('inactivo', 'Inactivo'), ('dado_de_baja', 'Dado de baja')], default='pendiente', max_length=30)),
                ('mostrar_contacto', models.BooleanField(default=True)),
                ('notas_internas', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Yonke',
                'verbose_name_plural': 'Yonkes',
                'ordering': ['nombre'],
            },
        ),
    ]
