# Generated by Django 6.0.5 on 2026-05-15 02:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('yonkes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('alias_local', models.CharField(blank=True, max_length=150)),
                ('marca_texto', models.CharField(blank=True, max_length=100)),
                ('modelo_texto', models.CharField(blank=True, max_length=100)),
                ('anio_inicio', models.PositiveIntegerField(blank=True, null=True)),
                ('anio_fin', models.PositiveIntegerField(blank=True, null=True)),
                ('condicion', models.CharField(choices=[('nueva', 'Nueva'), ('usada', 'Usada'), ('reparada', 'Reparada'), ('danada', 'Danada'), ('para_reparacion', 'Para reparacion'), ('desconocida', 'Desconocida')], default='usada', max_length=50)),
                ('estatus', models.CharField(choices=[('disponible', 'Disponible'), ('apartada', 'Apartada'), ('vendida', 'Vendida'), ('danada', 'Danada'), ('pendiente_revision', 'Pendiente de revision'), ('no_visible', 'No visible'), ('agotada', 'Agotada'), ('bloqueada', 'Bloqueada')], default='disponible', max_length=50)),
                ('visibilidad', models.CharField(choices=[('visible', 'Visible'), ('oculto', 'Oculto'), ('privado', 'Privado'), ('bloqueado', 'Bloqueado')], default='visible', max_length=30)),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_visible', models.BooleanField(default=False)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('ubicacion', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('ultima_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.categoriapieza')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('marca_compatible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.marca')),
                ('modelo_compatible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.modelovehiculo')),
                ('nombre_normalizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.nombrepieza')),
                ('yonke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piezas', to='yonkes.yonke')),
            ],
            options={
                'verbose_name': 'Pieza',
                'verbose_name_plural': 'Piezas',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.CreateModel(
            name='PiezaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='piezas/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.pieza')),
            ],
            options={
                'verbose_name': 'Imagen de pieza',
                'verbose_name_plural': 'Imagenes de piezas',
                'ordering': ['orden', 'creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_texto', models.CharField(blank=True, max_length=100)),
                ('modelo_texto', models.CharField(blank=True, max_length=100)),
                ('anio', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('motor', models.CharField(blank=True, max_length=100)),
                ('transmision', models.CharField(blank=True, max_length=100)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=50)),
                ('ubicacion_fisica', models.CharField(blank=True, max_length=150)),
                ('observaciones', models.TextField(blank=True)),
                ('datos_legales_internos', models.TextField(blank=True)),
                ('estatus', models.CharField(choices=[('disponible', 'Disponible'), ('en_revision', 'En revision'), ('en_desarme', 'En desarme'), ('parcialmente_desarmado', 'Parcialmente desarmado'), ('desarmado', 'Desarmado'), ('vendido_completo', 'Vendido completo'), ('dado_de_baja', 'Dado de baja'), ('archivado', 'Archivado'), ('bloqueado', 'Bloqueado'), ('en_revision_legal', 'En revision legal')], default='disponible', max_length=50)),
                ('visibilidad', models.CharField(choices=[('visible', 'Visible'), ('oculto', 'Oculto'), ('privado', 'Privado'), ('bloqueado', 'Bloqueado')], default='visible', max_length=30)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('ultima_actualizacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.marca')),
                ('modelo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.modelovehiculo')),
                ('yonke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='yonkes.yonke')),
            ],
            options={
                'verbose_name': 'Vehiculo',
                'verbose_name_plural': 'Vehiculos',
                'ordering': ['-actualizado_en'],
            },
        ),
        migrations.AddField(
            model_name='pieza',
            name='vehiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas', to='inventario.vehiculo'),
        ),
        migrations.CreateModel(
            name='VehiculoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='vehiculos/')),
                ('tipo', models.CharField(blank=True, max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='inventario.vehiculo')),
            ],
            options={
                'verbose_name': 'Imagen de vehiculo',
                'verbose_name_plural': 'Imagenes de vehiculos',
                'ordering': ['orden', 'creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='pieza',
            index=models.Index(fields=['nombre'], name='inventario__nombre_104981_idx'),
        ),
        migrations.AddIndex(
            model_name='pieza',
            index=models.Index(fields=['estatus'], name='inventario__estatus_f57957_idx'),
        ),
        migrations.AddIndex(
            model_name='pieza',
            index=models.Index(fields=['visibilidad'], name='inventario__visibil_ea651b_idx'),
        ),
        migrations.AddIndex(
            model_name='pieza',
            index=models.Index(fields=['ultima_actualizacion'], name='inventario__ultima__523cd4_idx'),
        ),
    ]
