# Generated by Django 6.0.5 on 2026-05-15 02:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('yonkes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportacionExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_importacion', models.CharField(choices=[('vehiculos', 'Vehiculos'), ('piezas', 'Piezas'), ('piezas_sueltas', 'Piezas sueltas'), ('mixto', 'Mixto')], max_length=50)),
                ('archivo', models.FileField(upload_to='importaciones/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('validando', 'Validando'), ('con_errores', 'Con errores'), ('lista_para_importar', 'Lista para importar'), ('importada', 'Importada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=50)),
                ('total_filas', models.PositiveIntegerField(default=0)),
                ('filas_validas', models.PositiveIntegerField(default=0)),
                ('filas_con_error', models.PositiveIntegerField(default=0)),
                ('resultado', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('yonke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='importaciones', to='yonkes.yonke')),
            ],
            options={
                'verbose_name': 'Importacion Excel',
                'verbose_name_plural': 'Importaciones Excel',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ImportacionError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fila', models.PositiveIntegerField()),
                ('campo', models.CharField(blank=True, max_length=100)),
                ('valor', models.TextField(blank=True)),
                ('error', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errores', to='importaciones.importacionexcel')),
            ],
            options={
                'verbose_name': 'Error de importacion',
                'verbose_name_plural': 'Errores de importacion',
                'ordering': ['numero_fila'],
            },
        ),
    ]
