# Generated by Django 6.0.5 on 2026-05-15 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Categoria de pieza',
                'verbose_name_plural': 'Categorias de piezas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NombrePieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_normalizado', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.categoriapieza')),
            ],
            options={
                'verbose_name': 'Nombre de pieza',
                'verbose_name_plural': 'Nombres de piezas',
                'ordering': ['nombre_normalizado'],
            },
        ),
        migrations.CreateModel(
            name='ModeloVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos', to='catalogos.marca')),
            ],
            options={
                'verbose_name': 'Modelo de vehiculo',
                'verbose_name_plural': 'Modelos de vehiculo',
                'ordering': ['marca__nombre', 'nombre'],
                'unique_together': {('marca', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='AliasPieza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=150)),
                ('nombre_pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias', to='catalogos.nombrepieza')),
            ],
            options={
                'verbose_name': 'Alias de pieza',
                'verbose_name_plural': 'Alias de piezas',
                'unique_together': {('nombre_pieza', 'alias')},
            },
        ),
    ]
