# Generated by Django 6.0.5 on 2026-06-28 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0001_initial"),
        ("yonkes", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="aliaspieza",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="modelovehiculo",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="aliaspieza",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="aliaspieza",
            name="yonke",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alias_piezas_catalogo",
                to="yonkes.yonke",
            ),
        ),
        migrations.AddField(
            model_name="categoriapieza",
            name="yonke",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="categorias_catalogo",
                to="yonkes.yonke",
            ),
        ),
        migrations.AddField(
            model_name="marca",
            name="yonke",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="marcas_catalogo",
                to="yonkes.yonke",
            ),
        ),
        migrations.AddField(
            model_name="modelovehiculo",
            name="yonke",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modelos_catalogo",
                to="yonkes.yonke",
            ),
        ),
        migrations.AddField(
            model_name="nombrepieza",
            name="yonke",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nombres_piezas_catalogo",
                to="yonkes.yonke",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aliaspieza",
            unique_together={("yonke", "nombre_pieza", "alias")},
        ),
        migrations.AlterUniqueTogether(
            name="modelovehiculo",
            unique_together={("yonke", "marca", "nombre")},
        ),
    ]
