# Generated by Django 6.0.5 on 2026-06-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0002_marca_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliaspieza",
            name="activo",
            field=models.BooleanField(default=True),
        ),
    ]
