# Generated by Django 6.0.5 on 2026-06-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0004_catalogos_operativos_yonke"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliaspieza",
            name="visibilidad",
            field=models.CharField(
                choices=[("privado", "Privado"), ("red", "Red")],
                default="privado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="categoriapieza",
            name="visibilidad",
            field=models.CharField(
                choices=[("privado", "Privado"), ("red", "Red")],
                default="privado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="marca",
            name="visibilidad",
            field=models.CharField(
                choices=[("privado", "Privado"), ("red", "Red")],
                default="privado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="modelovehiculo",
            name="visibilidad",
            field=models.CharField(
                choices=[("privado", "Privado"), ("red", "Red")],
                default="privado",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="nombrepieza",
            name="visibilidad",
            field=models.CharField(
                choices=[("privado", "Privado"), ("red", "Red")],
                default="privado",
                max_length=20,
            ),
        ),
    ]
