# Generated by Django 6.0.5 on 2026-06-28 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0005_catalogos_visibilidad_v1"),
        ("yonkes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aliaspieza",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="aliaspieza",
            name="yonke",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alias_piezas_catalogo",
                to="yonkes.yonke",
            ),
        ),
        migrations.AlterField(
            model_name="nombrepieza",
            name="yonke",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nombres_piezas_catalogo",
                to="yonkes.yonke",
            ),
        ),
    ]
